### ISSUE TITLE
openWifiSettings doesn't work on IOS

### ISSUE THREAD

**Issue by kintaroHorowitz** [mkloubert/nativescript-toolbox#1]
Function openWifiSettings works perfectly on my android device(old 4.4.2) but does not on 2 different iphones(5s/6s) with ios9 and ios10.

[ERROR] (nativescript-toolbox).openWifiSettings(): TypeError: UIApplication.sharedApplication is not a function. (In 'UIApplication.sharedApplication()', 'UIApplication.sharedApplication' is an instance of UIApplication)

**Comment by mkloubert** [comment]
@kintaroHorowitz 

**I have released version 1.49.0** that should fix the bug and be compatible with iOS 10.

**Comment by kintaroHorowitz** [comment]
Thanks that was fast.
Unfortunately I'm getting this error now:

node_modules/nativescript-toolbox/Device.ios.js:228:51)
Error: -[__NSCFString scheme]: unrecognized selector sent to instance 0x1702488e0

Sorry I can't help more to solve I'm beginner with nativescript.

**Comment by mkloubert** [comment]
@kintaroHorowitz 

Sorry, I submitted wrong data type. **Try 1.49.1...**

**Comment by kintaroHorowitz** [comment]
@mkloubert 

Thanks a lot, it is now working on both platforms.
